### ISSUE TITLE
Round 2 user research: cognitive walkthroughs 

### ISSUE THREAD

**Issue by kategarklavs** [18F/nsf-sbir#375]
Prior to the site's soft launch (6/23), we'd like to do a series of cognitive walkthroughs to make sure users can complete basic tasks:

- identify what the program is and what it offers
- determine whether their company is eligible (alt: succinctly describe what makes a company a good fit for the program, if said user is not an actual entrepreneur)
- describe the application process and how long it takes
- determine requirements of funded companies
- see what other companies similar to theirs have been funded
- And so on

Ideally, we'd like to conduct these walkthroughs with 1) eligible entrepreneurs who are wholly unfamiliar with America's Seed Fund; and 2) entrepreneurs we've already interviewed (who are familiar with the Seed Fund). Gathering data from both groups would allow us to determine whether the site's new messaging and information hierarchy resonate with totally new users, and would also help us figure out what we need to communicate more effectively to familiar users. Our goal is to interview between *four and six* users. 

Given our compressed timeframe, we may also conduct walkthroughs with members of the 18F internal team.

**To-dos**

- [x] ping research channel to recruit participants (6/15)
-  [x] draft research plan
- [x] revised research plan
- [x] interview (scheduled 06/26)
- [ ] interview (scheduled 06/26)
- [x] interview (scheduled 06/26)
- [x] interview (scheduled 06/27)
- [x] interview (scheduled 06/27)
- [x] synthesis
- [x] implement relevant changes 

cc @OpenGlobe

**Comment by kategarklavs** [comment]
@OpenGlobe - OK, just put together a draft research plan, which is here:

https://github.com/18F/nsf-sbir/wiki/Round-2-test-plan

(Note: This is a first draft and could probably use revision — please edit as you see fit!)

**Comment by OpenGlobe** [comment]
First three interviews scheduled.

**Comment by OpenGlobe** [comment]
https://github.com/18F/nsf-sbir/wiki/Research-synthesis,-Round-II
